### ISSUE TITLE
Scrolling down page reduces title font

### ISSUE THREAD

**Issue by TonyCMiller** [Dani3lSun/apex-plugin-irfixedtoolbar#1]
See attached images.  Running from demo page, using Firefox 38.4 ESR..
![header scroll 1](https://cloud.githubusercontent.com/assets/14878234/11790799/ced268da-a25a-11e5-80c9-856a6822bb41.PNG)
![header scroll 2](https://cloud.githubusercontent.com/assets/14878234/11790798/cecf26a2-a25a-11e5-9dec-0bd856663e58.PNG)
![header scroll 3](https://cloud.githubusercontent.com/assets/14878234/11790797/cec80fc0-a25a-11e5-8c4c-0b96db7d428e.PNG)

**Comment by Dani3lSun** [comment]
Hi Tony now I see what you mean...
If I understand you correct you mean the title included in the breadcrumb region position?
If so, this title changes font size even without my plugin, that is normal UT behaviour...
When scrolling down, the breadcrumb gets smaller and font changes.

Daniel

**Comment by Dani3lSun** [comment]
I´m closing this now, because that´s expected UT behaviour...
